# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://qipengliu.github.io/
baseurl: /
title: Qipeng Liu
author: Qipeng Liu
description: Personal website
avatar: photo.jpg
email: qpliu@ntu.edu.sg
github: qipengliu # username
#twitter: qipengliu
#linkedin: qipengliu
#stackoverflow: qipengliu   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
